###
GET http://localhost:4501/allBills

###
GET http://localhost:4501/oneBill/610a1c1a3fea2395b1f37ba0

###
GET http://localhost:4501/billsByCompany/6109db9feb28e118af55064a

###
POST http://localhost:4501/createBill
Content-Type: application/json

{
    "company" : "6109db9feb28e118af55064a",
    "article": [
        { 
            "product": "610a004b105d384a24fccc2f",
            "amount": 50,
            "price": 1.78
        }
    ]
}

###
PUT http://localhost:4501/cancelBill/610a1c1a3fea2395b1f37ba0
Content-Type: application/json

{
    "status": false
}

