###
GET http://localhost:4501/employees

###
GET http://localhost:4501/employee/6109dfc46067cb1fd9544a4d

###
GET http://localhost:4501/employeeCompany/6109db9feb28e118af55064a

###
GET http://localhost:4501/employeeEmail
Content-Type: application/json

{
    "email_": "david@gmail.com"
}

###
POST http://localhost:4501/addEmployee
Content-Type: application/json

{
    "name": "David Castillo",
    "email": "david@gmail.com",
    "company": "6109dcdd6b90531ad60ab4b2",
    "role": "0"
}

###
PUT http://localhost:4501/editEmployee/6109dfc46067cb1fd9544a4d
Content-Type: application/json

{
    "name": "David Castillo",
    "email": "david@gmail.com",
    "company": "6109dcdd6b90531ad60ab4b2",
    "status": false,
    "role": "1"
}

###
DELETE http://localhost:4501/deleteEmployee
Content-Type: application/json

{
    "delete_": "6109df486067cb1fd9544a3f"
}