version: "3.7"
services:
  frontend:
    container_name: frontend
    build:
      target: build
      context: client
    ports:
      - 3000:3000
    volumes:
      - /srv/app/node_modules
    tty: true
    depends_on:
      - strapi

  backend:
    container_name: backend
    build:
      target: build
      context: backend/
    volumes:
      - /srv/app/node_modules
    ports:
      - 4501:4501
    depends_on:
      - db
      - proxymanager

  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - AUTHENTICATION_DATABASE=strapi
    ports:
      - 1337:1337
    volumes:
      - ./server/app:/srv/app
      - /srv/app/node_modules
    depends_on:
      - db

  db:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always

  proxymanager:
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./proxymanager/config.json:/app/config/production.json
      - ./proxymanager/data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - proxymanagerdb
  proxymanagerdb:
    image: "jc21/mariadb-aria:10.4"
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - ./proxymanager/data/mysql:/var/lib/mysql
