version: "3.7"
services:
  frontend:
    container_name: frontend
    build:
      target: development
      context: client/
    command: yarn dev
    ports:
      - 3202:3000
    environment:
      HOST: "0.0.0.0"
    tty: true
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend
  strapi:
    container_name: strapi
    build:
      target: development
      context: server/app
    environment:
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - AUTHENTICATION_DATABASE=strapi
    ports:
      - 1337:1337
    volumes:
      - ./server/app:/srv/app
    depends_on:
      - db
  db:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always
