version: "3.7"
services:
  frontend:
    container_name: frontend
    build:
      target: build
      context: client
    command: yarn dev
    env_file: .env
    ports:
      - 3202:3000
    volumes:
      - ./client:/srv/app:cached
    environment:
      NODE_ENV: developer
      HOST: ${HOST}
      API_AUTH_URL: ${API_AUTH_URL}
      STRIPE_PK: ${STRIPE_PK}
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend
  strapi:
    container_name: strapi
    build:
      target: production
      context: server/app
    command: yarn start
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - AUTHENTICATION_DATABASE=strapi
    ports:
      - 1337:1337
    depends_on:
      - db
  db:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always
